### ISSUE TITLE
Events with Multiple Octopi printers

### ISSUE THREAD

**Issue by ioTataryn** [sedgett/OctoPrint_IFTTTmaker#16]
Hello, it would be useful to have customizable event names, so that multiple printers can be used.

Currently printer 1's event will fire and turn off printer 2.

Editable event names would fix this.  can you do this?

**Comment by jbeardon** [comment]
I'd like to +1 that suggestion, possibly replacing the 'op' at the beginning of the event name with an editable string or set of drop down values such as P1, P2, P3 etc?

Good work on the plugin. It's certainly the easiest way to get Octoprint and IFTTT up and running without involving multiple services. Having the ability to determine which printer is generating an event would be a welcome addition.

All the best.
JB

**Comment by hookemmike** [comment]
Bump, I have 2 printers running OctoPrint and would like to know which one notified me if I have them both running at the same time.

**Comment by jbeardon** [comment]
I've worked around this using an example on the [Octoprint event cookbook](https://github.com/foosel/OctoPrint/wiki/Cookbook:-Useful-Eventhooks#push-notifications-for-android--ios-via-ifttt):  in the 'Push notifications for Android / iOS via IFTTT' section.

You need to have the Yamlpatcher plugin installed and enabled. This is the code to be added via the YamlPatcher:

```
events:
  enabled: True
  subscriptions:
  - event: PrintDone
    command: curl -s
      -F "value1={name}"
      https://maker.ifttt.com/trigger/printername_print_done/with/key/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    type: system
```

Obviously change the printername bit on each of your octoprint instances to reference your printer. For your example p1_print_done, then look for that in IFTTT.  The xxxxxxxx bit is your IFTTT webhook key. 

Works a treat and within a few seconds of the print finishing.
